# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np


class Ui_Dialog(object):

    
        

    def setupUi(self, Dialog):
        self.function_to_apply_index = 0
        self.eliminate_noise_thold = 0.005
        self.num_of_training_days = 'All'
        self.last_n_days = 365  



        Dialog.setObjectName("Dialog")
        Dialog.resize(718, 522)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.general_settings_group = QtWidgets.QGroupBox(Dialog)
        self.general_settings_group.setObjectName("general_settings_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.general_settings_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.general_settings_group)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.comboBox = QtWidgets.QComboBox(self.general_settings_group)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.general_settings_group)

        self.training_settings_group = QtWidgets.QGroupBox(Dialog)
        self.training_settings_group.setObjectName("training_settings_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.training_settings_group)

        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.eliminate_noise_thold_label = QtWidgets.QLabel(self.training_settings_group)
        self.eliminate_noise_thold_label.setObjectName("eliminate_noise_thold_label")
        self.horizontalLayout_4.addWidget(self.eliminate_noise_thold_label)

        self.eliminate_noise_thold_edit = QtWidgets.QLineEdit(self.training_settings_group)
        self.eliminate_noise_thold_edit.setObjectName("eliminate_noise_thold_edit")
        self.horizontalLayout_4.addWidget(self.eliminate_noise_thold_edit)
        
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.training_days_label = QtWidgets.QLabel(self.training_settings_group)
        self.training_days_label.setObjectName("training_days_label")
        self.horizontalLayout_5.addWidget(self.training_days_label)

        self.all_radio_button = QtWidgets.QRadioButton(self.training_settings_group)
        self.all_radio_button.setObjectName("all_radio_button")
        self.all_radio_button.toggled.connect(self.disable_edit)
        self.horizontalLayout_5.addWidget(self.all_radio_button)

        self.custom_radio_button = QtWidgets.QRadioButton(self.training_settings_group)
        self.custom_radio_button.setObjectName("custom_radio_button")
        self.horizontalLayout_5.addWidget(self.custom_radio_button)


        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.label_2 = QtWidgets.QLabel(self.training_settings_group)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)

        self.training_days_edit = QtWidgets.QLineEdit(self.training_settings_group)
        self.training_days_edit.setObjectName("training_days_edit")
        self.horizontalLayout_2.addWidget(self.training_days_edit)

        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.training_settings_group)
        self.test_settings_group = QtWidgets.QGroupBox(Dialog)
        self.test_settings_group.setObjectName("test_settings_group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.test_settings_group)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.last_n_days_label = QtWidgets.QLabel(self.test_settings_group)
        self.last_n_days_label.setObjectName("last_n_days_label")
        self.horizontalLayout_6.addWidget(self.last_n_days_label)

        self.last_n_days_edit = QtWidgets.QLineEdit(self.test_settings_group)
        self.last_n_days_edit.setObjectName("last_n_days_edit")
        self.horizontalLayout_6.addWidget(self.last_n_days_edit)

        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)

        self.apply_changes_button = QtWidgets.QPushButton(self.test_settings_group)
        self.apply_changes_button.setObjectName("apply_changes_button")
        self.apply_changes_button.clicked.connect(lambda : self.apply_changes(Dialog))
        self.horizontalLayout_3.addWidget(self.apply_changes_button)

        self.cancel_button = QtWidgets.QPushButton(self.test_settings_group)
        self.cancel_button.setObjectName("cancel_button")
        self.cancel_button.clicked.connect(Dialog.accept)
        self.horizontalLayout_3.addWidget(self.cancel_button)

        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.test_settings_group)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.general_settings_group.setTitle(_translate("Dialog", "General"))
        self.label.setText(_translate("Dialog", "Function to apply"))
        self.comboBox.setItemText(0, _translate("Dialog", "Identity (No function)"))
        self.comboBox.setItemText(1, _translate("Dialog", "Sin"))
        self.comboBox.setItemText(2, _translate("Dialog", "Cos"))
        self.comboBox.setItemText(3, _translate("Dialog", "Tan"))
        self.training_settings_group.setTitle(_translate("Dialog", "Training settings"))
        self.eliminate_noise_thold_label.setText(_translate("Dialog", "Threshold for eliminating noise"))
        self.training_days_label.setText(_translate("Dialog", "Number of days for training"))
        self.all_radio_button.setText(_translate("Dialog", "All days"))
        self.custom_radio_button.setText(_translate("Dialog", "Custom"))
        self.label_2.setText(_translate("Dialog", "Please, select a number between 0 and 4000 "))
        self.test_settings_group.setTitle(_translate("Dialog", "Test Settings"))
        self.last_n_days_label.setText(_translate("Dialog", "Last n days.      n= "))
        self.apply_changes_button.setText(_translate("Dialog", "Apply changes"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))

    def disable_edit(self):
        if self.all_radio_button.isChecked():
            self.training_days_edit.setReadOnly(True)
            self.training_days_edit.setStyleSheet('background-color: gray')
            self.saved_num = self.training_days_edit.text()
            self.training_days_edit.setText('')
        else:
            self.training_days_edit.setReadOnly(False)
            self.training_days_edit.setStyleSheet('background-color: white')
            self.training_days_edit.setText(self.saved_num)
    
    
    def apply_changes(self, Dialog):
        self.function_to_apply_index = self.comboBox.currentIndex()
        self.eliminate_noise_thold = self.eliminate_noise_thold_edit.text()
        self.num_of_training_days = 'All' if self.all_radio_button.isChecked() else self.training_days_edit.text()
        self.last_n_days = self.last_n_days_edit.text()  

        
        print(f'{self.eliminate_noise_thold=}')
        print(f'{self.num_of_training_days=}')
        print(f'{self.last_n_days=}')

        Dialog.close()
